"""Instagram UI selectors.

The package is being reorganized by UI scope (`shell`, `surfaces`, `flows`,
`support`) while keeping the historical top-level imports stable.
"""

from .flows import UnfollowSelectors, UNFOLLOW_SELECTORS
from .shell import (
    AuthSelectors,
    AUTH_SELECTORS,
    ButtonSelectors,
    BUTTON_SELECTORS,
    DetectionSelectors,
    DETECTION_SELECTORS,
    NavigationSelectors,
    NAVIGATION_SELECTORS,
    PopupSelectors,
    POPUP_SELECTORS,
    ProblematicPageSelectors,
    PROBLEMATIC_PAGE_SELECTORS,
    TextInputSelectors,
    TEXT_INPUT_SELECTORS,
)
from .surfaces import (
    ContentCreationSelectors,
    CONTENT_CREATION_SELECTORS,
    DirectMessageSelectors,
    DM_SELECTORS,
    FeedSelectors,
    FEED_SELECTORS,
    FollowersListSelectors,
    FOLLOWERS_LIST_SELECTORS,
    HashtagSelectors,
    HASHTAG_SELECTORS,
    NotificationSelectors,
    NOTIFICATION_SELECTORS,
    PostSelectors,
    POST_SELECTORS,
    ProfileSelectors,
    PROFILE_SELECTORS,
    StorySelectors,
    STORY_SELECTORS,
)
from .support import DebugSelectors, DEBUG_SELECTORS, ScrollSelectors, SCROLL_SELECTORS

__all__ = [
    "AUTH_SELECTORS",
    "NAVIGATION_SELECTORS",
    "BUTTON_SELECTORS",
    "PROFILE_SELECTORS",
    "POST_SELECTORS",
    "STORY_SELECTORS",
    "DM_SELECTORS",
    "POPUP_SELECTORS",
    "SCROLL_SELECTORS",
    "DETECTION_SELECTORS",
    "TEXT_INPUT_SELECTORS",
    "PROBLEMATIC_PAGE_SELECTORS",
    "CONTENT_CREATION_SELECTORS",
    "DEBUG_SELECTORS",
    "FEED_SELECTORS",
    "UNFOLLOW_SELECTORS",
    "NOTIFICATION_SELECTORS",
    "HASHTAG_SELECTORS",
    "FOLLOWERS_LIST_SELECTORS",
    "AuthSelectors",
    "NavigationSelectors",
    "ButtonSelectors",
    "ProfileSelectors",
    "PostSelectors",
    "StorySelectors",
    "DirectMessageSelectors",
    "PopupSelectors",
    "ScrollSelectors",
    "DetectionSelectors",
    "TextInputSelectors",
    "ProblematicPageSelectors",
    "ContentCreationSelectors",
    "DebugSelectors",
    "FeedSelectors",
    "UnfollowSelectors",
    "NotificationSelectors",
    "HashtagSelectors",
    "FollowersListSelectors",
]
