-- TAKTIK local database: schema version 1, the baseline of the bot's objects.
-- Generated by scripts/build_schema_baseline.py from a base at the 1.9.8 schema.
-- Do not edit: a schema change is a new numbered migration.
-- The desktop app's own tables, views and triggers are not here: the app keeps them.

-- tables
CREATE TABLE filtered_profiles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      profile_id INTEGER NOT NULL,
      account_id INTEGER NOT NULL,
      username TEXT NOT NULL,
      filtered_at TEXT DEFAULT (datetime('now')),
      reason TEXT,
      source_type TEXT DEFAULT 'GENERAL',
      source_name TEXT DEFAULT 'unknown',
      session_id INTEGER,
      sync_id TEXT,
      UNIQUE(platform, profile_id, account_id)
    );

CREATE TABLE dm_threads (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      account_id INTEGER NOT NULL,
      partner_username TEXT NOT NULL,
      partner_profile_id INTEGER,
      external_thread_id TEXT,
      is_group INTEGER DEFAULT 0,
      can_reply INTEGER DEFAULT 1,
      last_message_text TEXT,
      last_message_at TEXT,
      last_message_is_ours INTEGER DEFAULT 0,
      unread_count INTEGER DEFAULT 0,
      message_count INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      sync_id TEXT,
      UNIQUE(platform, account_id, partner_username)
    );

CREATE TABLE dm_messages (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      thread_sync_id TEXT NOT NULL,
      account_id INTEGER,
      partner_username TEXT,
      direction TEXT NOT NULL,
      msg_type TEXT DEFAULT 'text',
      text TEXT,
      content_hash TEXT NOT NULL,
      seq INTEGER DEFAULT 0,
      sent_at TEXT DEFAULT (datetime('now')),
      displayed_at TEXT,
      ai_model TEXT,
      ai_cost_usd REAL,
      sync_id TEXT, reaction TEXT,
      UNIQUE(platform, thread_sync_id, direction, content_hash)
    );

CREATE TABLE notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      account_id INTEGER NOT NULL,
      actor_username TEXT,
      actor_profile_id INTEGER,
      type TEXT,
      raw_category TEXT,
      label TEXT,
      body TEXT,
      relative_time TEXT,
      has_action INTEGER DEFAULT 0,
      attributed INTEGER DEFAULT 0,
      attribution_type TEXT,
      attribution_at TEXT,
      content_hash TEXT NOT NULL,
      first_seen_at TEXT DEFAULT (datetime('now')),
      last_seen_at TEXT DEFAULT (datetime('now')),
      sync_id TEXT,
      UNIQUE(platform, account_id, content_hash)
    );

CREATE TABLE account_restriction_signals (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      account_username TEXT NOT NULL,
      detected_at TEXT DEFAULT (datetime('now')),
      signal TEXT NOT NULL DEFAULT 'private_first_ordering',
      source_type TEXT,
      source_name TEXT,
      source_followers INTEGER,
      streak INTEGER,
      encounter_order INTEGER,
      jump_index INTEGER,
      gestures INTEGER,
      session_id INTEGER,
      sync_id TEXT
    );

CREATE TABLE posted_comments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      account_id INTEGER,
      session_id INTEGER,
      target_username TEXT NOT NULL,
      post_author TEXT,
      post_ref TEXT,
      post_url TEXT,
      post_caption TEXT,
      post_description TEXT,
      kind TEXT NOT NULL DEFAULT 'comment',
      reply_to_username TEXT,
      reply_to_text TEXT,
      comment_text TEXT NOT NULL,
      source TEXT NOT NULL DEFAULT 'ai',
      ai_model TEXT,
      ai_cost_usd REAL,
      ai_reasoning TEXT,
      language TEXT,
      posted_at TEXT DEFAULT (datetime('now')),
      created_at TEXT DEFAULT (datetime('now')),
      sync_id TEXT
    );

CREATE TABLE device_identity (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        device_id TEXT NOT NULL,
        created_at TEXT DEFAULT (datetime('now'))
      );

CREATE TABLE interactions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        platform TEXT NOT NULL DEFAULT 'instagram',
        legacy_id INTEGER,
        session_id INTEGER,
        account_id INTEGER,
        profile_id INTEGER,
        interaction_type TEXT NOT NULL,
        success INTEGER DEFAULT 1,
        content TEXT,
        video_id TEXT,
        interaction_time TEXT DEFAULT (datetime('now')),
        created_at TEXT DEFAULT (datetime('now')),
        sync_id TEXT,
        account_username TEXT,
        target_username TEXT,
        origin_device_id TEXT,
        session_sync_id TEXT, source TEXT DEFAULT 'bot',
        UNIQUE(platform, legacy_id)
      );

CREATE TABLE daily_stats_unified (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        platform TEXT NOT NULL DEFAULT 'instagram',
        account_id INTEGER NOT NULL,
        date TEXT NOT NULL,
        total_likes INTEGER DEFAULT 0,
        total_follows INTEGER DEFAULT 0,
        total_unfollows INTEGER DEFAULT 0,
        total_comments INTEGER DEFAULT 0,
        total_profile_visits INTEGER DEFAULT 0,
        total_story_views INTEGER DEFAULT 0,
        total_story_likes INTEGER DEFAULT 0,
        total_favorites INTEGER DEFAULT 0,
        total_shares INTEGER DEFAULT 0,
        total_posts_watched INTEGER DEFAULT 0,
        total_sessions INTEGER DEFAULT 0,
        completed_sessions INTEGER DEFAULT 0,
        failed_sessions INTEGER DEFAULT 0,
        total_duration_seconds INTEGER DEFAULT 0,
        synced_to_api INTEGER DEFAULT 0,
        synced_at TEXT,
        created_at TEXT DEFAULT (datetime('now')),
        updated_at TEXT DEFAULT (datetime('now')),
        UNIQUE(platform, account_id, date)
      );

CREATE TABLE sessions_unified (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        platform TEXT NOT NULL DEFAULT 'instagram',
        legacy_session_id INTEGER,
        account_id INTEGER,
        session_name TEXT,
        target_type TEXT,
        workflow_type TEXT,
        target TEXT,
        start_time TEXT,
        end_time TEXT,
        duration_seconds INTEGER,
        config_used TEXT,
        status TEXT,
        error_message TEXT,
        synced_to_api INTEGER DEFAULT 0,
        ai_total_cost_usd REAL DEFAULT 0,
        ai_profiles_analyzed INTEGER DEFAULT 0,
        ai_posts_analyzed INTEGER DEFAULT 0,
        ai_comments_generated INTEGER DEFAULT 0,
        stats_total_interactions INTEGER DEFAULT 0,
        stats_likes INTEGER DEFAULT 0,
        stats_follows INTEGER DEFAULT 0,
        stats_unfollows INTEGER DEFAULT 0,
        stats_comments INTEGER DEFAULT 0,
        stats_story_views INTEGER DEFAULT 0,
        stats_story_likes INTEGER DEFAULT 0,
        stats_profile_visits INTEGER DEFAULT 0,
        profiles_visited INTEGER DEFAULT 0,
        posts_watched INTEGER DEFAULT 0,
        likes INTEGER DEFAULT 0,
        follows INTEGER DEFAULT 0,
        favorites INTEGER DEFAULT 0,
        comments INTEGER DEFAULT 0,
        shares INTEGER DEFAULT 0,
        errors INTEGER DEFAULT 0,
        videos_watched INTEGER DEFAULT 0,
        ai_cost_by_kind TEXT,
        stop_reason_code TEXT,
        stop_reason_params TEXT,
        created_at TEXT DEFAULT (datetime('now')),
        updated_at TEXT DEFAULT (datetime('now')),
        sync_id TEXT,
        UNIQUE(platform, legacy_session_id)
      );

CREATE TABLE "scraped_profiles" (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL DEFAULT 'instagram',
            scraping_id INTEGER NOT NULL,
            profile_id INTEGER NOT NULL,
            scraped_at TEXT DEFAULT (datetime('now')),
            is_enriched INTEGER DEFAULT 0,
            ai_score INTEGER,
            ai_qualified INTEGER DEFAULT 0,
            ai_analysis TEXT,
            qualification_criteria TEXT,
            scored_at TEXT,
            source_post_url TEXT,
            UNIQUE(scraping_id, profile_id)
          );

CREATE TABLE "social_graph_sync" (
        id INTEGER PRIMARY KEY AUTOINCREMENT, platform TEXT NOT NULL DEFAULT 'instagram', account_id INTEGER NOT NULL,
        username TEXT NOT NULL COLLATE NOCASE, direction TEXT NOT NULL, display_name TEXT DEFAULT '',
        is_reciprocal INTEGER DEFAULT NULL, followed_by_bot INTEGER DEFAULT 0, unfollowed_at TEXT DEFAULT NULL,
        first_seen_at TEXT DEFAULT (datetime('now')), last_seen_at TEXT DEFAULT (datetime('now')),
        source TEXT DEFAULT 'sync', UNIQUE(platform, account_id, username, direction));

CREATE TABLE "profile_stats_history" (
        id INTEGER PRIMARY KEY AUTOINCREMENT, profile_id INTEGER NOT NULL, followers_count INTEGER NOT NULL,
        following_count INTEGER NOT NULL, posts_count INTEGER NOT NULL, engagement_rate REAL, is_verified INTEGER,
        biography TEXT, external_url TEXT, profile_pic_url TEXT, recorded_at TEXT DEFAULT (datetime('now')),
        is_business INTEGER DEFAULT 0, category TEXT, sync_id TEXT, username TEXT);

CREATE TABLE accounts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          platform TEXT NOT NULL DEFAULT 'instagram',
          legacy_account_id INTEGER,
          username TEXT NOT NULL,
          is_bot INTEGER DEFAULT 1,
          user_id INTEGER,
          license_id INTEGER,
          display_name TEXT,
          qualification_prompt TEXT,
          bio TEXT,
          niche TEXT,
          product_service TEXT,
          objective TEXT,
          target_audience TEXT,
          tone_personality TEXT,
          preferred_language TEXT,
          website TEXT,
          unique_selling_point TEXT,
          custom_context TEXT,
          created_at TEXT DEFAULT (datetime('now')),
          updated_at TEXT DEFAULT (datetime('now')),
          sync_id TEXT, warmup_intensity TEXT, warmup_preset_id INTEGER,
          UNIQUE(platform, legacy_account_id)
        );

CREATE TABLE social_profiles (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          platform TEXT NOT NULL DEFAULT 'instagram',
          legacy_profile_id INTEGER,
          username TEXT NOT NULL,
          display_name TEXT DEFAULT '',
          biography TEXT,
          followers_count INTEGER DEFAULT 0,
          following_count INTEGER DEFAULT 0,
          posts_count INTEGER DEFAULT 0,
          likes_count INTEGER DEFAULT 0,
          is_private INTEGER DEFAULT 0,
          is_verified INTEGER DEFAULT 0,
          is_business INTEGER DEFAULT 0,
          business_category TEXT,
          website TEXT,
          profile_pic_path TEXT,
          ai_screenshot_path TEXT,
          notes TEXT,
          account_based_in TEXT,
          date_joined TEXT,
          location_city TEXT,
          location_region TEXT,
          primary_language TEXT,
          created_at TEXT DEFAULT (datetime('now')),
          updated_at TEXT DEFAULT (datetime('now')),
          sync_id TEXT, unreachable_at TEXT, unreachable_count INTEGER DEFAULT 0,
          UNIQUE(platform, legacy_profile_id)
        );

CREATE TABLE "sent_dms" (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      account_id INTEGER NOT NULL,
      recipient_username TEXT NOT NULL,
      message_hash TEXT,
      sent_at TEXT DEFAULT (datetime('now')),
      success INTEGER DEFAULT 1,
      error_message TEXT,
      session_id TEXT,
      sync_id TEXT,
      platform TEXT NOT NULL DEFAULT 'instagram',
      UNIQUE(account_id, recipient_username, platform));

CREATE TABLE scraping_sessions (
            scraping_id INTEGER PRIMARY KEY AUTOINCREMENT,
            account_id INTEGER,
            scraping_type TEXT NOT NULL,
            source_type TEXT NOT NULL,
            source_name TEXT NOT NULL,
            total_scraped INTEGER DEFAULT 0,
            max_profiles INTEGER DEFAULT 500,
            export_csv INTEGER DEFAULT 0,
            csv_path TEXT,
            save_to_db INTEGER DEFAULT 1,
            start_time TEXT DEFAULT (datetime('now')),
            end_time TEXT,
            duration_seconds INTEGER DEFAULT 0,
            status TEXT DEFAULT 'RUNNING',
            error_message TEXT,
            config_used TEXT,
            platform TEXT DEFAULT 'instagram',
            sync_id TEXT,
            created_at TEXT DEFAULT (datetime('now'))
        , updated_at TEXT);

CREATE TABLE processed_hashtag_posts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            account_id INTEGER NOT NULL,
            hashtag TEXT NOT NULL,
            post_author TEXT NOT NULL,
            post_caption_hash TEXT,
            post_caption_preview TEXT,
            likes_count INTEGER,
            comments_count INTEGER,
            likers_processed INTEGER DEFAULT 0,
            interactions_made INTEGER DEFAULT 0,
            processed_at TEXT DEFAULT (datetime('now')),
            UNIQUE(account_id, hashtag, post_author, post_caption_hash)
        );

CREATE TABLE profile_following (
            id                 INTEGER PRIMARY KEY AUTOINCREMENT,
            profile_username   TEXT NOT NULL,
            profile_id         INTEGER,
            following_username TEXT NOT NULL,
            following_id       INTEGER,
            session_id         TEXT,
            discovered_at      TEXT DEFAULT (datetime('now')), niche_category TEXT, niche TEXT, gender TEXT, classified_at TEXT,
            UNIQUE(profile_username, following_username)
        );

CREATE TABLE notification_actions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL DEFAULT 'instagram',
            account_id INTEGER NOT NULL,
            content_hash TEXT,
            actor_username TEXT,
            action TEXT NOT NULL,
            source TEXT NOT NULL DEFAULT 'manual',
            success INTEGER NOT NULL DEFAULT 1,
            created_at TEXT DEFAULT (datetime('now'))
        );

CREATE TABLE post_analysis (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL DEFAULT 'instagram',
            post_ref TEXT NOT NULL,
            post_author TEXT,
            post_caption TEXT,
            description TEXT,
            post_language TEXT,
            ai_model TEXT,
            ai_cost_usd REAL,
            hit_count INTEGER DEFAULT 0,
            analyzed_at TEXT DEFAULT (datetime('now')),
            last_used_at TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            sync_id TEXT,
            UNIQUE(platform, post_ref)
        );

CREATE TABLE ai_prompt_bodies (
            hash TEXT PRIMARY KEY,
            kind TEXT NOT NULL,
            body TEXT NOT NULL,
            chars INTEGER,
            first_seen_at TEXT DEFAULT (datetime('now')),
            last_seen_at TEXT DEFAULT (datetime('now')),
            uses INTEGER NOT NULL DEFAULT 0
        );

CREATE TABLE ai_call_captures (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL DEFAULT 'instagram',
            kind TEXT NOT NULL,
            username TEXT,
            comment_id INTEGER,
            captured_at TEXT DEFAULT (datetime('now')),
            model TEXT,
            prompt_hash TEXT,
            user_prompt TEXT,
            persona TEXT,
            meta TEXT
        );

CREATE TABLE social_posts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            platform TEXT NOT NULL DEFAULT 'instagram',
            post_key TEXT NOT NULL,
            post_url TEXT NOT NULL,
            author_username TEXT NOT NULL,
            likes_count INTEGER,
            comments_count INTEGER,
            first_seen_at TEXT DEFAULT (datetime('now')),
            last_scraped_at TEXT DEFAULT (datetime('now')),
            sync_id TEXT,
            UNIQUE(platform, post_key)
        );

CREATE TABLE ai_benchmark_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            started_at TEXT NOT NULL DEFAULT (datetime('now')),
            finished_at TEXT,
            status TEXT NOT NULL DEFAULT 'running',
            seed INTEGER,
            sample_size INTEGER,
            budget_usd REAL,
            total_cost_usd REAL DEFAULT 0,
            config TEXT,
            note TEXT
        );

CREATE TABLE ai_benchmark_results (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_id INTEGER NOT NULL,
            task TEXT NOT NULL,
            case_ref TEXT NOT NULL,
            model TEXT NOT NULL,
            served_model TEXT,
            cost_usd REAL,
            seconds REAL,
            baseline TEXT,
            candidate TEXT,
            agreement TEXT,
            created_at TEXT NOT NULL DEFAULT (datetime('now'))
        );

CREATE TABLE feed_ads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            creative_hash TEXT NOT NULL UNIQUE,
            advertiser TEXT,
            account_id INTEGER,
            platform TEXT NOT NULL DEFAULT 'instagram',
            screenshot BLOB,
            ocr_text TEXT,
            ai_analysis TEXT,
            ai_analyzed_at TEXT,
            times_seen INTEGER NOT NULL DEFAULT 1,
            first_seen_at TEXT DEFAULT (datetime('now')),
            last_seen_at TEXT DEFAULT (datetime('now'))
        );

CREATE TABLE content_relays (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            account_id INTEGER,
            platform TEXT NOT NULL DEFAULT 'instagram',
            source_username TEXT NOT NULL,
            media_signature TEXT NOT NULL,
            kind TEXT NOT NULL DEFAULT 'story',
            status TEXT NOT NULL,
            reason TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        );

-- indexes
CREATE INDEX idx_account_restriction_account
      ON account_restriction_signals(platform, account_username, detected_at);

CREATE UNIQUE INDEX idx_account_restriction_sync_id
      ON account_restriction_signals(sync_id);

CREATE INDEX idx_posted_comments_session ON posted_comments(platform, session_id);

CREATE INDEX idx_posted_comments_target ON posted_comments(platform, target_username);

CREATE INDEX idx_posted_comments_account ON posted_comments(platform, account_id, posted_at);

CREATE UNIQUE INDEX idx_posted_comments_sync_id ON posted_comments(sync_id);

CREATE INDEX idx_filtered_account ON filtered_profiles(account_id);

CREATE INDEX idx_filtered_username ON filtered_profiles(username);

CREATE UNIQUE INDEX idx_filtered_profiles_sync_id ON filtered_profiles(sync_id);

CREATE INDEX idx_interactions_account ON interactions(platform, account_id, interaction_type);

CREATE INDEX idx_interactions_profile ON interactions(platform, profile_id);

CREATE INDEX idx_interactions_time ON interactions(interaction_time);

CREATE INDEX idx_interactions_session ON interactions(platform, session_id);

CREATE UNIQUE INDEX idx_interactions_sync_id ON interactions(sync_id);

CREATE INDEX idx_daily_stats_unified_account ON daily_stats_unified(platform, account_id, date);

CREATE INDEX idx_sessions_unified_account ON sessions_unified(platform, account_id);

CREATE UNIQUE INDEX idx_sessions_unified_sync_id ON sessions_unified(sync_id);

CREATE INDEX idx_dm_threads_account ON dm_threads(platform, account_id);

CREATE INDEX idx_dm_threads_partner ON dm_threads(platform, partner_username);

CREATE UNIQUE INDEX idx_dm_threads_sync_id ON dm_threads(sync_id);

CREATE INDEX idx_dm_messages_thread ON dm_messages(thread_sync_id, seq);

CREATE UNIQUE INDEX idx_dm_messages_sync_id ON dm_messages(sync_id);

CREATE INDEX idx_posted_comments_kind ON posted_comments(platform, kind);

CREATE INDEX idx_scraped_profiles_session ON scraped_profiles(scraping_id);

CREATE INDEX idx_scraped_profiles_profile ON scraped_profiles(profile_id);

CREATE INDEX idx_scraped_profiles_qualified ON scraped_profiles(ai_qualified);

CREATE INDEX idx_scraped_profiles_score ON scraped_profiles(ai_score);

CREATE INDEX idx_scraped_profiles_post_url ON scraped_profiles(source_post_url) WHERE source_post_url IS NOT NULL;

CREATE INDEX idx_social_graph_sync_account ON social_graph_sync(account_id, direction);

CREATE INDEX idx_social_graph_sync_username ON social_graph_sync(account_id, username);

CREATE INDEX idx_stats_profile_date ON profile_stats_history(profile_id, recorded_at);

CREATE INDEX idx_stats_recorded ON profile_stats_history(recorded_at);

CREATE UNIQUE INDEX idx_accounts_unified_username ON accounts(platform, username);

CREATE INDEX idx_social_profiles_unreachable ON social_profiles(platform, unreachable_at);

CREATE UNIQUE INDEX idx_social_profiles_username ON social_profiles(platform, username);

CREATE INDEX idx_social_profiles_platform_created ON social_profiles(platform, created_at);

CREATE INDEX idx_social_profiles_country ON social_profiles(platform, account_based_in);

CREATE INDEX idx_social_profiles_city ON social_profiles(platform, location_city);

CREATE INDEX idx_social_profiles_region ON social_profiles(platform, location_region);

CREATE INDEX idx_interactions_profile_type
               ON interactions(platform, profile_id, interaction_type, interaction_time);

CREATE INDEX idx_filtered_profiles_source
               ON filtered_profiles(platform, source_name);

CREATE INDEX idx_interactions_target
               ON interactions(platform, target_username);

CREATE INDEX idx_social_profiles_geo_cov
               ON social_profiles(platform, account_based_in, location_region, location_city, followers_count, username);

CREATE INDEX idx_social_profiles_updated ON social_profiles(updated_at);

CREATE INDEX idx_interactions_window_cov
               ON interactions(platform, interaction_time, interaction_type, success, account_id, session_id, profile_id);

CREATE INDEX idx_interactions_session_cov
               ON interactions(platform, session_id, interaction_time, success, interaction_type);

CREATE INDEX idx_interactions_profile_first
               ON interactions(platform, profile_id, success, interaction_time);

CREATE INDEX idx_sessions_unified_window
               ON sessions_unified(platform, start_time);

CREATE INDEX idx_sessions_unified_target
               ON sessions_unified(platform, target);

CREATE INDEX idx_sent_dms_account ON sent_dms(account_id);

CREATE INDEX idx_sent_dms_recipient ON sent_dms(recipient_username);

CREATE UNIQUE INDEX idx_sent_dms_sync_id ON sent_dms(sync_id);

CREATE INDEX idx_scraping_sessions_status ON scraping_sessions(status);

CREATE INDEX idx_scraping_sessions_source ON scraping_sessions(source_type, source_name);

CREATE INDEX idx_scraping_sessions_type ON scraping_sessions(scraping_type, start_time DESC);

CREATE INDEX idx_processed_hashtag_posts_lookup ON processed_hashtag_posts(account_id, hashtag, post_author);

CREATE INDEX idx_profile_following_profile ON profile_following(profile_username);

CREATE INDEX idx_profile_following_following ON profile_following(following_username);

CREATE INDEX idx_notifications_account ON notifications(platform, account_id, last_seen_at);

CREATE INDEX idx_notifications_actor ON notifications(platform, actor_username);

CREATE UNIQUE INDEX idx_notifications_sync_id ON notifications(sync_id);

CREATE INDEX idx_notification_actions_account ON notification_actions(platform, account_id, action, created_at);

CREATE INDEX idx_notification_actions_hash ON notification_actions(platform, account_id, content_hash);

CREATE INDEX idx_post_analysis_author ON post_analysis(platform, post_author);

CREATE UNIQUE INDEX idx_post_analysis_sync_id ON post_analysis(sync_id);

CREATE INDEX idx_ai_call_captures_recent ON ai_call_captures(kind, captured_at DESC);

CREATE INDEX idx_ai_call_captures_username ON ai_call_captures(platform, kind, username);

CREATE INDEX idx_ai_call_captures_comment ON ai_call_captures(comment_id) WHERE comment_id IS NOT NULL;

CREATE INDEX idx_social_posts_author ON social_posts(platform, author_username, likes_count DESC);

CREATE UNIQUE INDEX idx_social_posts_sync_id ON social_posts(sync_id);

CREATE INDEX idx_social_posts_url ON social_posts(platform, post_url);

CREATE INDEX idx_ai_benchmark_results_run ON ai_benchmark_results(run_id, task);

CREATE INDEX idx_ai_benchmark_results_model ON ai_benchmark_results(model, task);

CREATE INDEX idx_profile_following_niche_category ON profile_following(niche_category);

CREATE INDEX idx_feed_ads_times_seen ON feed_ads(times_seen DESC);

CREATE INDEX idx_feed_ads_advertiser ON feed_ads(advertiser);

CREATE INDEX idx_feed_ads_pending_ai ON feed_ads(ai_analyzed_at) WHERE ai_analyzed_at IS NULL;

CREATE UNIQUE INDEX idx_content_relays_signature ON content_relays(account_id, platform, source_username, media_signature);

CREATE INDEX idx_content_relays_recent ON content_relays(account_id, created_at DESC);

CREATE INDEX idx_profile_stats_history_recorded ON profile_stats_history(recorded_at);

CREATE INDEX idx_social_profiles_username_ci ON social_profiles(platform, lower(username));

CREATE INDEX idx_accounts_username_ci ON accounts(platform, lower(username));

CREATE INDEX idx_profile_following_following_lower
               ON profile_following(lower(following_username));

-- views
CREATE VIEW instagram_profiles AS SELECT
          legacy_profile_id AS profile_id, username, display_name AS full_name, biography,
          followers_count, following_count, posts_count, is_private, profile_pic_path, notes,
          created_at, updated_at, is_verified, is_business, business_category, website,
          NULL AS linked_accounts, NULL AS ai_niche, NULL AS ai_score, NULL AS ai_classification,
          NULL AS ai_classified_at, ai_screenshot_path, account_based_in, date_joined, location_city,
          NULL AS ai_specific_niche, NULL AS ai_profession, NULL AS ai_profession_tags,
          NULL AS ai_gender, NULL AS ai_age_group, location_region
        FROM social_profiles WHERE platform = 'instagram';

CREATE VIEW tiktok_profiles AS SELECT
          legacy_profile_id AS profile_id, username, display_name, followers_count, following_count,
          likes_count, posts_count AS videos_count, is_private, is_verified, biography,
          created_at, updated_at, profile_pic_path
        FROM social_profiles WHERE platform = 'tiktok';
