"""UI module for TikTok - Selectors and detectors."""

from .selectors import (
    AUTH_SELECTORS,
    NAVIGATION_SELECTORS,
    PROFILE_SELECTORS,
    VIDEO_SELECTORS,
    COMMENT_SELECTORS,
    SEARCH_SELECTORS,
    POPUP_SELECTORS,
    SCROLL_SELECTORS,
    DETECTION_SELECTORS
)

__all__ = [
    'AUTH_SELECTORS',
    'NAVIGATION_SELECTORS',
    'PROFILE_SELECTORS',
    'VIDEO_SELECTORS',
    'COMMENT_SELECTORS',
    'SEARCH_SELECTORS',
    'POPUP_SELECTORS',
    'SCROLL_SELECTORS',
    'DETECTION_SELECTORS'
]
