"""Generate schema migration 1 (the bot's baseline) and the schema manifest.

    python scripts/build_schema_baseline.py --from-code   # rebuild the 1.9.8 schema from both halves, then generate
    python scripts/build_schema_baseline.py --from PATH   # generate from a base at the 1.9.8 schema
    python scripts/build_schema_baseline.py --manifest    # rewrite schema_manifest.json only
    python scripts/build_schema_baseline.py --check       # exit 1 when the manifest is stale
    python scripts/build_schema_baseline.py --check-code  # exit 1 when the baseline no longer matches the code

Until 1.9.9 ships, every schema change in the un-numbered code (the app's migrations.ts on a table
of the bot, or the bot's own schema steps) must be followed by `--from-code`.

Only the bot's objects go into the baseline: the tables its own steps create (plus `sent_dms`,
created by its repository), the indexes on those tables, and the views that read nothing else.
The desktop app's tables, its views and every trigger stay the app's. The source is opened
read-only and only its schema is read: no row, name or path reaches the generated files, and the
comments of the original CREATE statements are dropped.

The baseline also lists the retired tables: tables the bot's steps once created or drop. A base
that still has one has not finished its 1.9.8 migrations and is not recognised.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from taktik.core.database.local.versions.backup import connect_read_only  # noqa: E402
from taktik.core.database.local.versions.catalog import VERSIONS_DIR  # noqa: E402
from taktik.core.database.local.versions.fingerprint import fingerprint, scope  # noqa: E402
from taktik.core.database.local.versions.sql_text import split_statements, strip_comments  # noqa: E402

BASELINE_SQL = VERSIONS_DIR / "m0001_baseline.sql"
BASELINE_FINGERPRINT = VERSIONS_DIR / "baseline_fingerprint.json"
BASELINE_RETIRED = VERSIONS_DIR / "m0001_retired_tables.json"

_KIND_ORDER = ("table", "index", "view")
_KIND_TITLE = {"table": "tables", "index": "indexes", "view": "views"}
_CREATE_TABLE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[\"'`]?(\w+)", re.I)
_DROP_TABLE = re.compile(r"DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?[\"'`]?(\w+)", re.I)
_ALTER_RENAME = re.compile(r"ALTER\s+TABLE\s+[\"'`]?(\w+)[\"'`]?\s+RENAME\s+TO", re.I)

FORBIDDEN = {
    "clock time": re.compile(r"\b(?:[01]?\d|2[0-3]):[0-5]\d\b"),
    "Windows path": re.compile(r"[A-Za-z]:[\\/]"),
    "home path": re.compile(r"/(?:Users|home)/", re.I),
    "e-mail": re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"),
}

HEADER = """-- TAKTIK local database: schema version 1, the baseline of the bot's objects.
-- Generated by scripts/build_schema_baseline.py from a base at the 1.9.8 schema.
-- Do not edit: a schema change is a new numbered migration.
-- The desktop app's own tables, views and triggers are not here: the app keeps them.
"""


def bot_steps() -> Dict[str, set]:
    """What the bot's own un-numbered steps leave in an empty base, and every table they
    create or drop on the way (traced).

    `sent_dms` is created lazily by its repository, not by the steps: the bot writes it.
    """
    from taktik.core.database.local.migrations import run_migrations
    from taktik.core.database.local.schema import create_schema
    from taktik.core.database.repositories.messaging.sent_dm_repository import SentDMRepository

    statements: List[str] = []
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    try:
        conn.set_trace_callback(statements.append)
        create_schema(conn)
        run_migrations(conn)
        SentDMRepository(conn).ensure_table()
        conn.set_trace_callback(None)
        final: Dict[str, set] = {"table": set(), "view": set(), "index": set(), "trigger": set()}
        for row in conn.execute("SELECT type, name FROM sqlite_master"):
            final.setdefault(row["type"], set()).add(row["name"])
    finally:
        conn.close()
    script = "\n".join(statements)
    touched = set(_CREATE_TABLE.findall(script)) | set(_DROP_TABLE.findall(script)) | set(_ALTER_RENAME.findall(script))
    return {"tables": final["table"], "views": final["view"], "touched_tables": touched}


def read_source(path: Path) -> Tuple[List[Tuple[str, str, str, str]], Dict]:
    conn = connect_read_only(path)
    try:
        if conn.execute("PRAGMA user_version").fetchone()[0] != 0:
            raise SystemExit("the source is already numbered: take a base at the 1.9.8 schema")
        rows = conn.execute(
            "SELECT type, name, tbl_name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\' ORDER BY rowid"
        ).fetchall()
        if any(name == "schema_migrations" for _, name, _, _ in rows):
            raise SystemExit("the source carries a schema journal: take a base at the 1.9.8 schema")
        return rows, fingerprint(conn)
    finally:
        conn.close()


def _views_readable_alone(table_statements: List[str], views: List[Tuple[str, str]]) -> List[str]:
    """Views that resolve with the bot's tables alone (so they read nothing of the app)."""
    conn = sqlite3.connect(":memory:")
    try:
        for statement in table_statements:
            conn.execute(statement)
        keep = []
        for name, sql in views:
            conn.execute(sql)
            try:
                conn.execute(f'PRAGMA table_xinfo("{name}")').fetchall()
                keep.append(name)
            except sqlite3.Error:
                pass
        return keep
    finally:
        conn.close()


def select_bot_objects(rows, bot: Dict[str, set]):
    source_tables = {name for typ, name, _, _ in rows if typ == "table"}
    bot_relations = bot["tables"] | bot["views"] | {"sent_dms"}
    tables = [(name, sql) for typ, name, _, sql in rows if typ == "table" and name in bot_relations]
    table_names = {name for name, _ in tables}
    indexes = [(name, sql) for typ, name, tbl, sql in rows if typ == "index" and tbl in table_names]
    candidate_views = [(name, sql) for typ, name, _, sql in rows if typ == "view" and name in bot_relations]
    readable = set(_views_readable_alone([sql for _, sql in tables], candidate_views))
    views = [(name, sql) for name, sql in candidate_views if name in readable]
    retired = sorted(bot["touched_tables"] - table_names)
    clash = sorted(set(retired) & source_tables)
    if clash:
        raise SystemExit(f"refused: retired tables still exist as tables in the source: {clash}")
    return tables, indexes, views, retired


def render(tables, indexes, views) -> str:
    parts = [HEADER]
    for kind, items in (("table", tables), ("index", indexes), ("view", views)):
        if not items:
            continue
        parts.append(f"\n-- {_KIND_TITLE[kind]}\n")
        parts.append("\n\n".join(strip_comments(sql).strip() + ";" for _, sql in items) + "\n")
    return "".join(parts)


def normalized_objects(conn, names=None) -> Dict[Tuple[str, str], str]:
    return {
        (typ, name): " ".join(strip_comments(sql).split())
        for typ, name, sql in conn.execute(
            "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL "
            "AND name NOT LIKE 'sqlite\\_%' ESCAPE '\\'"
        )
        if names is None or name in names
    }


def verify(text: str, source: Path, expected: Dict, names: set) -> None:
    for label, pattern in FORBIDDEN.items():
        found = pattern.search(text)
        if found:
            raise SystemExit(f"refused: the baseline contains a {label}: {found.group(0)!r}")
    conn = sqlite3.connect(":memory:", isolation_level=None)
    try:
        conn.execute("BEGIN")
        for statement in split_statements(text):
            if not statement.upper().startswith("CREATE"):
                raise SystemExit(f"refused: the baseline may only create objects: {statement[:60]}")
            conn.execute(statement)
        conn.execute("COMMIT")
        fp = fingerprint(conn)
        rebuilt = scope(fp, fp["tables"], fp["views"], fp["triggers"], expected["retired_tables"])
        rebuilt_sql = normalized_objects(conn)
    finally:
        conn.close()
    broken = [name for name, cols in rebuilt["views"].items() if isinstance(cols, str)]
    if broken:
        raise SystemExit(f"refused: views of the baseline read objects it does not create: {broken}")
    if rebuilt != expected:
        raise SystemExit("refused: the baseline does not rebuild the bot's part of the source (fingerprint)")
    src = connect_read_only(source)
    try:
        original = normalized_objects(src, names)
    finally:
        src.close()
    if rebuilt_sql != original:
        missing = sorted(set(original) - set(rebuilt_sql))
        changed = sorted(k for k in set(original) & set(rebuilt_sql) if original[k] != rebuilt_sql[k])
        raise SystemExit(f"refused: objects differ from the source (missing {missing[:5]}, changed {changed[:5]})")


def generate(source: Path) -> Dict[Path, str]:
    """The three baseline files, as text, for the base at `source`."""
    rows, source_fp = read_source(source)
    tables, indexes, views, retired = select_bot_objects(rows, bot_steps())
    text = render(tables, indexes, views)
    expected = scope(source_fp, [n for n, _ in tables], [n for n, _ in views], [], retired)
    names = {n for n, _ in tables} | {n for n, _ in indexes} | {n for n, _ in views}
    verify(text, source, expected, names)
    return {
        BASELINE_SQL: text,
        BASELINE_FINGERPRINT: json.dumps(expected, indent=1, sort_keys=True) + "\n",
        BASELINE_RETIRED: json.dumps(retired, indent=1) + "\n",
    }


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="")


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""


def check_code() -> List[str]:
    """Stale files, if the baseline no longer matches what the code of both halves builds."""
    from build_schema_fixpoint import build

    with tempfile.TemporaryDirectory(prefix="schema-baseline-") as tmp:
        fixpoint = Path(tmp) / "fixpoint.db"
        build(fixpoint)
        files = generate(fixpoint)
    return [path.name for path, text in files.items() if _read(path) != text]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--from", dest="source", type=Path)
    group.add_argument("--from-code", action="store_true")
    group.add_argument("--manifest", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--check-code", action="store_true")
    args = parser.parse_args(argv)

    if args.check_code:
        stale = check_code()
        if stale:
            print(f"the baseline no longer matches the code ({', '.join(stale)}): "
                  "run scripts/build_schema_baseline.py --from-code")
            return 1
        args.check = True

    if args.source or args.from_code:
        if args.from_code:
            from build_schema_fixpoint import build

            with tempfile.TemporaryDirectory(prefix="schema-baseline-") as tmp:
                fixpoint = Path(tmp) / "fixpoint.db"
                build(fixpoint)
                files = generate(fixpoint)
        else:
            files = generate(args.source)
        for path, text in files.items():
            write_text(path, text)
        print(f"wrote {', '.join(p.name for p in files)}")

    from taktik.core.database.local.versions.manifest import MANIFEST_PATH, build_manifest, render_manifest

    expected = render_manifest(build_manifest())
    if args.check:
        if _read(MANIFEST_PATH) != expected:
            print("schema_manifest.json is stale: run scripts/build_schema_baseline.py --manifest")
            return 1
        print("baseline and schema_manifest.json are up to date")
        return 0
    write_text(MANIFEST_PATH, expected)
    print(f"wrote {MANIFEST_PATH.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
