"""The vocabulary of the bot/app contract: settings a workflow reads, events a bridge prints.

A declaration is plain data. It is the single source of three things:
- the payload readers, which `tests/unit/app/contract` holds to it (keys read, defaults, aliases,
  refusals);
- the desktop app's TypeScript types, generated by `scripts/workflow_contract.py`;
- the app's gates, which read it instead of re-deriving the bot side from the source.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Optional, Tuple, Union


class _NoDefault:
    """No default: absent means absent (or refused, when the field is required)."""

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "NO_DEFAULT"


NO_DEFAULT = _NoDefault()


@dataclass(frozen=True)
class Computed:
    """A default the reader computes at run time (the device id, a timestamp)."""

    description: str


#: Scalar types: "int", "number", "bool", "string", "json" (any JSON value).
SCALARS = ("int", "number", "bool", "string", "json")


@dataclass(frozen=True)
class OneOf:
    """One of a closed set of strings."""

    values: Tuple[str, ...]


@dataclass(frozen=True)
class ListOf:
    item: "TypeSpec"


@dataclass(frozen=True)
class MapOf:
    """An object whose keys are data (a motive, a name) and whose values share one type."""

    value: "TypeSpec"


@dataclass(frozen=True)
class Shape:
    """A named object with declared fields."""

    name: str
    fields: Tuple["Field", ...]
    doc: str = ""


TypeSpec = Union[str, OneOf, ListOf, MapOf, Shape]

#: Who fills a field: the operator (a page, a scheduler node, a CLI argument) or the host process
#: that launches the bridge (the device id, a session id, an API key).
OPERATOR = "operator"
HOST = "host"


@dataclass(frozen=True)
class Field:
    """One key of a payload or of an event.

    key       the name on the wire, the one the app sends or receives
    type      a scalar name or a TypeSpec
    default   the value the reader applies when the key is absent
    required  the run is refused without it
    aliases   other names the reader accepts (CLI, Agent plan, older app), in its order of preference
    attr      the attribute of the reader's result that the key sets (conformance test)
    negate    the attribute holds the opposite of the key (`skip_friends` sets `include_friends`)
    reader    "module:function" reading this key alone, when the contract's reader does not
    by        OPERATOR or HOST
    app       False: accepted from the CLI or an Agent plan only, never sent by the app
    nullable  the value may be null (events)
    optional  events: the key may be missing from the line
    """

    key: str
    type: TypeSpec
    doc: str = ""
    default: Any = NO_DEFAULT
    required: bool = False
    aliases: Tuple[str, ...] = ()
    attr: Optional[str] = None
    negate: bool = False
    reader: Optional[str] = None
    by: str = OPERATOR
    app: bool = True
    nullable: bool = False
    optional: bool = False

    @property
    def names(self) -> Tuple[str, ...]:
        return (self.key, *self.aliases)


@dataclass(frozen=True)
class Refusal:
    """The run is refused before the phone is touched when `missing` is absent or empty."""

    missing: str
    when: Mapping[str, Any] = field(default_factory=dict)
    doc: str = ""


@dataclass(frozen=True)
class Event:
    """One JSON line a bridge prints on stdout, named by its `type`."""

    type: str
    fields: Tuple[Field, ...]
    doc: str = ""


@dataclass(frozen=True)
class WorkflowContract:
    """What one workflow of the manifest reads, and what its bridge prints.

    workflow_id     the id of `workflows.manifest.json`
    name            the prefix of the generated TypeScript names
    bridge          the name in `bridges/bridges.manifest.json`
    launcher        "module:function" of the one launcher (`run_*`) the CLI and the bridge call
    reader          "module:function" turning a payload into the workflow's config, called by the
                    launcher
    reader_kwargs   keyword arguments the reader needs besides the payload
    settings        read by the launcher: everything a CLI run can set
    bridge_fields   read by the bridge alone (device, IP rotation): the CLI host fills them itself
    nest            the key of the bridge file under which the settings travel, if any
    beside_settings bridge fields that travel under `nest`, next to the settings
    events          the lines of the bridge's stdout the app reads
    refusals        what the launcher refuses before the phone is touched
    """

    workflow_id: str
    name: str
    bridge: str
    launcher: str
    reader: str
    settings: Tuple[Field, ...]
    doc: str = ""
    reader_kwargs: Mapping[str, Any] = field(default_factory=dict)
    bridge_fields: Tuple[Field, ...] = ()
    nest: Optional[str] = None
    beside_settings: Tuple[str, ...] = ()
    events: Tuple[Event, ...] = ()
    refusals: Tuple[Refusal, ...] = ()

    def setting(self, key: str) -> Field:
        for item in self.settings:
            if item.key == key:
                return item
        raise KeyError(key)

    def event(self, event_type: str) -> Event:
        for item in self.events:
            if item.type == event_type:
                return item
        raise KeyError(event_type)


def has_default(item: Field) -> bool:
    return item.default is not NO_DEFAULT and not isinstance(item.default, Computed)


__all__ = [
    "Computed",
    "Event",
    "Field",
    "HOST",
    "ListOf",
    "MapOf",
    "NO_DEFAULT",
    "OPERATOR",
    "OneOf",
    "Refusal",
    "SCALARS",
    "Shape",
    "TypeSpec",
    "WorkflowContract",
    "has_default",
]
